package oog.macros;/* This file was generated by SableCC's ObjectMacro. */


class CacheBuilder {

    private String expansion = null;

    public String getExpansion() {
        return expansion;
    }

    public void setExpansion(
            String expansion) {

        this.expansion = expansion;
    }
}