package oog.macros;/* This file was generated by SableCC's ObjectMacro. */


class InternalsInitializer {

    private final String _paramName;

    InternalsInitializer(String paramName) {
        this._paramName = paramName;
    }

    void setMainClass(MMainClass mMainClass) {
        throw ObjectMacroException.incorrectType("MMainClass", this._paramName);
    }
    
    void setVariable(MVariable mVariable) {
        throw ObjectMacroException.incorrectType("MVariable", this._paramName);
    }
    
    void setEventif(MEventif mEventif) {
        throw ObjectMacroException.incorrectType("MEventif", this._paramName);
    }
    
    void setIfstatement(MIfstatement mIfstatement) {
        throw ObjectMacroException.incorrectType("MIfstatement", this._paramName);
    }
    
    void setModifier(MModifier mModifier) {
        throw ObjectMacroException.incorrectType("MModifier", this._paramName);
    }

    void setObjectMacroUserErrorHead(MObjectMacroUserErrorHead mObjectMacroUserErrorHead) {
        throw ObjectMacroException.incorrectType("MObjectMacroUserErrorHead", this._paramName);
    }

    void setUserErrorIncorrectType(MUserErrorIncorrectType mUserErrorIncorrectType) {
        throw ObjectMacroException.incorrectType("MUserErrorIncorrectType", this._paramName);
    }

    void setUserErrorMacroNullInList(MUserErrorMacroNullInList mUserErrorMacroNullInList) {
        throw ObjectMacroException.incorrectType("MUserErrorMacroNullInList", this._paramName);
    }

    void setUserErrorCyclicReference(MUserErrorCyclicReference mUserErrorCyclicReference) {
        throw ObjectMacroException.incorrectType("MUserErrorCyclicReference", this._paramName);
    }

    void setUserErrorParameterNull(MUserErrorParameterNull mUserErrorParameterNull) {
        throw ObjectMacroException.incorrectType("MUserErrorParameterNull", this._paramName);
    }

    void setUserErrorCannotModify(MUserErrorCannotModify mUserErrorCannotModify) {
        throw ObjectMacroException.incorrectType("MUserErrorCannotModify", this._paramName);
    }

    void setUserErrorVersionNull(MUserErrorVersionNull mUserErrorVersionNull) {
        throw ObjectMacroException.incorrectType("MUserErrorVersionNull", this._paramName);
    }

    void setUserErrorVersionsDifferent(MUserErrorVersionsDifferent mUserErrorVersionsDifferent) {
        throw ObjectMacroException.incorrectType("MUserErrorVersionsDifferent", this._paramName);
    }

    void setUserErrorInternalException(MUserErrorInternalException mUserErrorInternalException) {
        throw ObjectMacroException.incorrectType("MUserErrorInternalException", this._paramName);
    }

}