package oog.macros;/* This file was generated by SableCC's ObjectMacro. */

import java.util.List;

public class Macros {

    private VERSIONS version;

    public Macros(
            VERSIONS version){

        if(version == null){
            throw ObjectMacroException.versionNull();
        }

        this.version = version;
    }

    public Macros(){
        this.version = null;
    }
    
    public MMainClass newMainClass(){
        MMainClass mMainClass;
    
        mMainClass = new MMainClass(this);
    
        return mMainClass;
    }
    
    public MMainClass newMainClass(List<Macro> pVar, List<Macro> pStm){
        MMainClass mMainClass;
    
        mMainClass = new MMainClass(pVar, pStm, this);
    
        return mMainClass;
    }
    
    public MVariable newVariable(){
        MVariable mVariable;
    
        mVariable = new MVariable(this);
    
        return mVariable;
    }
    
    public MVariable newVariable(String pMin, String pMax, String pDef, String pVisible, String pName){
        MVariable mVariable;
    
        mVariable = new MVariable(pMin, pMax, pDef, pVisible, pName, this);
    
        return mVariable;
    }
    
    public MEventif newEventif(){
        MEventif mEventif;
    
        mEventif = new MEventif(this);
    
        return mEventif;
    }
    
    public MEventif newEventif(List<Macro> pStm, String pCurrentevent){
        MEventif mEventif;
    
        mEventif = new MEventif(pStm, pCurrentevent, this);
    
        return mEventif;
    }
    
    public MIfstatement newIfstatement(){
        MIfstatement mIfstatement;
    
        mIfstatement = new MIfstatement(this);
    
        return mIfstatement;
    }
    
    public MIfstatement newIfstatement(String pExit, String pNextevent, List<Macro> pModifiers){
        MIfstatement mIfstatement;
    
        mIfstatement = new MIfstatement(pExit, pNextevent, pModifiers, this);
    
        return mIfstatement;
    }
    
    public MModifier newModifier(){
        MModifier mModifier;
    
        mModifier = new MModifier(this);
    
        return mModifier;
    }
    
    public MModifier newModifier(String pVariable, String pValue, String pOperator){
        MModifier mModifier;
    
        mModifier = new MModifier(pVariable, pValue, pOperator, this);
    
        return mModifier;
    }
}