/* This file was generated by SableCC (http://www.sablecc.org/). */

package oog.syntax.analysis;

import oog.syntax.node.*;

public interface Analysis extends Switch
{
    Object getIn(Node node);
    void setIn(Node node, Object o);
    Object getOut(Node node);
    void setOut(Node node, Object o);

    void caseStart(Start node);
    void caseAProgram(AProgram node);
    void caseAVariabledef(AVariabledef node);
    void caseAEventdef(AEventdef node);
    void caseAExitlist(AExitlist node);
    void caseAExitstm(AExitstm node);
    void caseAModifierlist(AModifierlist node);
    void caseAPlusModifier(APlusModifier node);
    void caseAMinusModifier(AMinusModifier node);
    void caseAEqualModifier(AEqualModifier node);

    void caseTPlus(TPlus node);
    void caseTMinus(TMinus node);
    void caseTLSqPar(TLSqPar node);
    void caseTRSqPar(TRSqPar node);
    void caseTLBrace(TLBrace node);
    void caseTRBrace(TRBrace node);
    void caseTArrow(TArrow node);
    void caseTEqual(TEqual node);
    void caseTDotDot(TDotDot node);
    void caseTVar(TVar node);
    void caseTExit(TExit node);
    void caseTEvent(TEvent node);
    void caseTVisibility(TVisibility node);
    void caseTDefault(TDefault node);
    void caseTNum(TNum node);
    void caseTIdent(TIdent node);
    void caseTComment(TComment node);
    void caseTBlank(TBlank node);
    void caseEOF(EOF node);
    void caseInvalidToken(InvalidToken node);
}
