/* This file was generated by SableCC (http://www.sablecc.org/). */

package oog.syntax.parser;

import oog.syntax.lexer.*;
import oog.syntax.node.*;
import oog.syntax.analysis.*;
import java.util.*;

import java.io.DataInputStream;
import java.io.BufferedInputStream;
import java.io.IOException;

@SuppressWarnings("nls")
public class Parser
{
    public final Analysis ignoredTokens = new AnalysisAdapter();

    protected ArrayList<Object> nodeList;

    private final Lexer lexer;
    private final ListIterator<Object> stack = new LinkedList<Object>().listIterator();
    private int last_pos;
    private int last_line;
    private Token last_token;
    private final TokenIndex converter = new TokenIndex();
    private final int[] action = new int[2];

    private final static int SHIFT = 0;
    private final static int REDUCE = 1;
    private final static int ACCEPT = 2;
    private final static int ERROR = 3;

    public Parser(@SuppressWarnings("hiding") Lexer lexer)
    {
        this.lexer = lexer;
    }

    protected void filter() throws ParserException, LexerException, IOException
    {
        // Empty body
    }

    private void push(int numstate, ArrayList<Object> listNode, boolean hidden) throws ParserException, LexerException, IOException
    {
        this.nodeList = listNode;

        if(!hidden)
        {
            filter();
        }

        if(!this.stack.hasNext())
        {
            this.stack.add(new State(numstate, this.nodeList));
            return;
        }

        State s = (State) this.stack.next();
        s.state = numstate;
        s.nodes = this.nodeList;
    }

    private int goTo(int index)
    {
        int state = state();
        int low = 1;
        int high = gotoTable[index].length - 1;
        int value = gotoTable[index][0][1];

        while(low <= high)
        {
            // int middle = (low + high) / 2;
            int middle = (low + high) >>> 1;

            if(state < gotoTable[index][middle][0])
            {
                high = middle - 1;
            }
            else if(state > gotoTable[index][middle][0])
            {
                low = middle + 1;
            }
            else
            {
                value = gotoTable[index][middle][1];
                break;
            }
        }

        return value;
    }

    private int state()
    {
        State s = (State) this.stack.previous();
        this.stack.next();
        return s.state;
    }

    private ArrayList<Object> pop()
    {
        return ((State) this.stack.previous()).nodes;
    }

    private int index(Switchable token)
    {
        this.converter.index = -1;
        token.apply(this.converter);
        return this.converter.index;
    }

    @SuppressWarnings("unchecked")
    public Start parse() throws ParserException, LexerException, IOException
    {
        push(0, null, true);
        List<Node> ign = null;
        while(true)
        {
            while(index(this.lexer.peek()) == -1)
            {
                if(ign == null)
                {
                    ign = new LinkedList<Node>();
                }

                ign.add(this.lexer.next());
            }

            if(ign != null)
            {
                this.ignoredTokens.setIn(this.lexer.peek(), ign);
                ign = null;
            }

            this.last_pos = this.lexer.peek().getPos();
            this.last_line = this.lexer.peek().getLine();
            this.last_token = this.lexer.peek();

            int index = index(this.lexer.peek());
            this.action[0] = Parser.actionTable[state()][0][1];
            this.action[1] = Parser.actionTable[state()][0][2];

            int low = 1;
            int high = Parser.actionTable[state()].length - 1;

            while(low <= high)
            {
                int middle = (low + high) / 2;

                if(index < Parser.actionTable[state()][middle][0])
                {
                    high = middle - 1;
                }
                else if(index > Parser.actionTable[state()][middle][0])
                {
                    low = middle + 1;
                }
                else
                {
                    this.action[0] = Parser.actionTable[state()][middle][1];
                    this.action[1] = Parser.actionTable[state()][middle][2];
                    break;
                }
            }

            switch(this.action[0])
            {
                case SHIFT:
		    {
		        ArrayList<Object> list = new ArrayList<Object>();
		        list.add(this.lexer.next());
                        push(this.action[1], list, false);
                    }
		    break;
                case REDUCE:
                    {
                        int reduction = this.action[1];
                        if(reduction < 500) reduce_0(reduction);
                    }
                    break;
                case ACCEPT:
                    {
                        EOF node2 = (EOF) this.lexer.next();
                        PProgram node1 = (PProgram) pop().get(0);
                        Start node = new Start(node1, node2);
                        return node;
                    }
                case ERROR:
                    throw new ParserException(this.last_token,
                        "[" + this.last_line + "," + this.last_pos + "] " +
                        Parser.errorMessages[Parser.errors[this.action[1]]]);
            }
        }
    }

    private void reduce_0(int reduction) throws IOException, LexerException, ParserException
    {
        switch(reduction)
        {
            case 0: /* reduce AAprogram1Program */
            {
                ArrayList<Object> list = new0();
                push(goTo(0), list, false);
            }
            break;
            case 1: /* reduce AAprogram2Program */
            {
                ArrayList<Object> list = new1();
                push(goTo(0), list, false);
            }
            break;
            case 2: /* reduce AAprogram3Program */
            {
                ArrayList<Object> list = new2();
                push(goTo(0), list, false);
            }
            break;
            case 3: /* reduce AAprogram4Program */
            {
                ArrayList<Object> list = new3();
                push(goTo(0), list, false);
            }
            break;
            case 4: /* reduce AVariabledef */
            {
                ArrayList<Object> list = new4();
                push(goTo(1), list, false);
            }
            break;
            case 5: /* reduce AEventdef */
            {
                ArrayList<Object> list = new5();
                push(goTo(2), list, false);
            }
            break;
            case 6: /* reduce AAexitlist1Exitlist */
            {
                ArrayList<Object> list = new6();
                push(goTo(3), list, false);
            }
            break;
            case 7: /* reduce AAexitlist2Exitlist */
            {
                ArrayList<Object> list = new7();
                push(goTo(3), list, false);
            }
            break;
            case 8: /* reduce AAexitstm1Exitstm */
            {
                ArrayList<Object> list = new8();
                push(goTo(4), list, false);
            }
            break;
            case 9: /* reduce AAexitstm2Exitstm */
            {
                ArrayList<Object> list = new9();
                push(goTo(4), list, false);
            }
            break;
            case 10: /* reduce AAmodifierlist1Modifierlist */
            {
                ArrayList<Object> list = new10();
                push(goTo(5), list, false);
            }
            break;
            case 11: /* reduce AAmodifierlist2Modifierlist */
            {
                ArrayList<Object> list = new11();
                push(goTo(5), list, false);
            }
            break;
            case 12: /* reduce APlusModifier */
            {
                ArrayList<Object> list = new12();
                push(goTo(6), list, false);
            }
            break;
            case 13: /* reduce AMinusModifier */
            {
                ArrayList<Object> list = new13();
                push(goTo(6), list, false);
            }
            break;
            case 14: /* reduce AEqualModifier */
            {
                ArrayList<Object> list = new14();
                push(goTo(6), list, false);
            }
            break;
            case 15: /* reduce ATerminal$Variabledef */
            {
                ArrayList<Object> list = new15();
                push(goTo(7), list, true);
            }
            break;
            case 16: /* reduce ANonTerminal$Variabledef */
            {
                ArrayList<Object> list = new16();
                push(goTo(7), list, true);
            }
            break;
            case 17: /* reduce ATerminal$Eventdef */
            {
                ArrayList<Object> list = new17();
                push(goTo(8), list, true);
            }
            break;
            case 18: /* reduce ANonTerminal$Eventdef */
            {
                ArrayList<Object> list = new18();
                push(goTo(8), list, true);
            }
            break;
            case 19: /* reduce ATerminal$Exitstm */
            {
                ArrayList<Object> list = new19();
                push(goTo(9), list, true);
            }
            break;
            case 20: /* reduce ANonTerminal$Exitstm */
            {
                ArrayList<Object> list = new20();
                push(goTo(9), list, true);
            }
            break;
            case 21: /* reduce ATerminal$Modifier */
            {
                ArrayList<Object> list = new21();
                push(goTo(10), list, true);
            }
            break;
            case 22: /* reduce ANonTerminal$Modifier */
            {
                ArrayList<Object> list = new22();
                push(goTo(10), list, true);
            }
            break;
        }
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new0() /* reduce AAprogram1Program */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        PProgram pprogramNode1;
        {
            // Block
        LinkedList<Object> listNode2 = new LinkedList<Object>();
        LinkedList<Object> listNode3 = new LinkedList<Object>();
        {
            // Block
        }
        {
            // Block
        }

        pprogramNode1 = new AProgram(listNode2, listNode3);
        }
	nodeList.add(pprogramNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new1() /* reduce AAprogram2Program */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PProgram pprogramNode1;
        {
            // Block
        LinkedList<Object> listNode3 = new LinkedList<Object>();
        LinkedList<Object> listNode4 = new LinkedList<Object>();
        {
            // Block
        LinkedList<Object> listNode2 = new LinkedList<Object>();
        listNode2 = (LinkedList)nodeArrayList1.get(0);
	if(listNode2 != null)
	{
	  listNode3.addAll(listNode2);
	}
        }
        {
            // Block
        }

        pprogramNode1 = new AProgram(listNode3, listNode4);
        }
	nodeList.add(pprogramNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new2() /* reduce AAprogram3Program */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PProgram pprogramNode1;
        {
            // Block
        LinkedList<Object> listNode2 = new LinkedList<Object>();
        LinkedList<Object> listNode4 = new LinkedList<Object>();
        {
            // Block
        }
        {
            // Block
        LinkedList<Object> listNode3 = new LinkedList<Object>();
        listNode3 = (LinkedList)nodeArrayList1.get(0);
	if(listNode3 != null)
	{
	  listNode4.addAll(listNode3);
	}
        }

        pprogramNode1 = new AProgram(listNode2, listNode4);
        }
	nodeList.add(pprogramNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new3() /* reduce AAprogram4Program */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PProgram pprogramNode1;
        {
            // Block
        LinkedList<Object> listNode3 = new LinkedList<Object>();
        LinkedList<Object> listNode5 = new LinkedList<Object>();
        {
            // Block
        LinkedList<Object> listNode2 = new LinkedList<Object>();
        listNode2 = (LinkedList)nodeArrayList1.get(0);
	if(listNode2 != null)
	{
	  listNode3.addAll(listNode2);
	}
        }
        {
            // Block
        LinkedList<Object> listNode4 = new LinkedList<Object>();
        listNode4 = (LinkedList)nodeArrayList2.get(0);
	if(listNode4 != null)
	{
	  listNode5.addAll(listNode4);
	}
        }

        pprogramNode1 = new AProgram(listNode3, listNode5);
        }
	nodeList.add(pprogramNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new4() /* reduce AVariabledef */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList6 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PVariabledef pvariabledefNode1;
        {
            // Block
        TVar tvarNode2;
        TIdent tidentNode3;
        TVisibility tvisibilityNode4;
        TNum tnumNode5;
        TNum tnumNode6;
        TNum tnumNode7;
        tvarNode2 = (TVar)nodeArrayList1.get(0);
        tidentNode3 = (TIdent)nodeArrayList2.get(0);
        tvisibilityNode4 = (TVisibility)nodeArrayList3.get(0);
        tnumNode5 = (TNum)nodeArrayList4.get(0);
        tnumNode6 = (TNum)nodeArrayList5.get(0);
        tnumNode7 = (TNum)nodeArrayList6.get(0);

        pvariabledefNode1 = new AVariabledef(tvarNode2, tidentNode3, tvisibilityNode4, tnumNode5, tnumNode6, tnumNode7);
        }
	nodeList.add(pvariabledefNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new5() /* reduce AEventdef */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PEventdef peventdefNode1;
        {
            // Block
        TEvent teventNode2;
        TIdent tidentNode3;
        TDotDot tdotdotNode4;
        PExitlist pexitlistNode5;
        teventNode2 = (TEvent)nodeArrayList1.get(0);
        tidentNode3 = (TIdent)nodeArrayList2.get(0);
        tdotdotNode4 = (TDotDot)nodeArrayList3.get(0);
        pexitlistNode5 = (PExitlist)nodeArrayList4.get(0);

        peventdefNode1 = new AEventdef(teventNode2, tidentNode3, tdotdotNode4, pexitlistNode5);
        }
	nodeList.add(peventdefNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new6() /* reduce AAexitlist1Exitlist */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PExitlist pexitlistNode1;
        {
            // Block
        TLBrace tlbraceNode2;
        LinkedList<Object> listNode3 = new LinkedList<Object>();
        TRBrace trbraceNode4;
        tlbraceNode2 = (TLBrace)nodeArrayList1.get(0);
        {
            // Block
        }
        trbraceNode4 = (TRBrace)nodeArrayList2.get(0);

        pexitlistNode1 = new AExitlist(tlbraceNode2, listNode3, trbraceNode4);
        }
	nodeList.add(pexitlistNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new7() /* reduce AAexitlist2Exitlist */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PExitlist pexitlistNode1;
        {
            // Block
        TLBrace tlbraceNode2;
        LinkedList<Object> listNode4 = new LinkedList<Object>();
        TRBrace trbraceNode5;
        tlbraceNode2 = (TLBrace)nodeArrayList1.get(0);
        {
            // Block
        LinkedList<Object> listNode3 = new LinkedList<Object>();
        listNode3 = (LinkedList)nodeArrayList2.get(0);
	if(listNode3 != null)
	{
	  listNode4.addAll(listNode3);
	}
        }
        trbraceNode5 = (TRBrace)nodeArrayList3.get(0);

        pexitlistNode1 = new AExitlist(tlbraceNode2, listNode4, trbraceNode5);
        }
	nodeList.add(pexitlistNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new8() /* reduce AAexitstm1Exitstm */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PExitstm pexitstmNode1;
        {
            // Block
        TExit texitNode2;
        TNum tnumNode3;
        TArrow tarrowNode4;
        TIdent tidentNode5;
        @SuppressWarnings("unused") Object nullNode6 = null;
        texitNode2 = (TExit)nodeArrayList1.get(0);
        tnumNode3 = (TNum)nodeArrayList2.get(0);
        tarrowNode4 = (TArrow)nodeArrayList3.get(0);
        tidentNode5 = (TIdent)nodeArrayList4.get(0);

        pexitstmNode1 = new AExitstm(texitNode2, tnumNode3, tarrowNode4, tidentNode5, null);
        }
	nodeList.add(pexitstmNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new9() /* reduce AAexitstm2Exitstm */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PExitstm pexitstmNode1;
        {
            // Block
        TExit texitNode2;
        TNum tnumNode3;
        TArrow tarrowNode4;
        TIdent tidentNode5;
        PModifierlist pmodifierlistNode6;
        texitNode2 = (TExit)nodeArrayList1.get(0);
        tnumNode3 = (TNum)nodeArrayList2.get(0);
        tarrowNode4 = (TArrow)nodeArrayList3.get(0);
        tidentNode5 = (TIdent)nodeArrayList4.get(0);
        pmodifierlistNode6 = (PModifierlist)nodeArrayList5.get(0);

        pexitstmNode1 = new AExitstm(texitNode2, tnumNode3, tarrowNode4, tidentNode5, pmodifierlistNode6);
        }
	nodeList.add(pexitstmNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new10() /* reduce AAmodifierlist1Modifierlist */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PModifierlist pmodifierlistNode1;
        {
            // Block
        TLSqPar tlsqparNode2;
        LinkedList<Object> listNode3 = new LinkedList<Object>();
        TRSqPar trsqparNode4;
        tlsqparNode2 = (TLSqPar)nodeArrayList1.get(0);
        {
            // Block
        }
        trsqparNode4 = (TRSqPar)nodeArrayList2.get(0);

        pmodifierlistNode1 = new AModifierlist(tlsqparNode2, listNode3, trsqparNode4);
        }
	nodeList.add(pmodifierlistNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new11() /* reduce AAmodifierlist2Modifierlist */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PModifierlist pmodifierlistNode1;
        {
            // Block
        TLSqPar tlsqparNode2;
        LinkedList<Object> listNode4 = new LinkedList<Object>();
        TRSqPar trsqparNode5;
        tlsqparNode2 = (TLSqPar)nodeArrayList1.get(0);
        {
            // Block
        LinkedList<Object> listNode3 = new LinkedList<Object>();
        listNode3 = (LinkedList)nodeArrayList2.get(0);
	if(listNode3 != null)
	{
	  listNode4.addAll(listNode3);
	}
        }
        trsqparNode5 = (TRSqPar)nodeArrayList3.get(0);

        pmodifierlistNode1 = new AModifierlist(tlsqparNode2, listNode4, trsqparNode5);
        }
	nodeList.add(pmodifierlistNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new12() /* reduce APlusModifier */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PModifier pmodifierNode1;
        {
            // Block
        TIdent tidentNode2;
        TPlus tplusNode3;
        TNum tnumNode4;
        tidentNode2 = (TIdent)nodeArrayList1.get(0);
        tplusNode3 = (TPlus)nodeArrayList2.get(0);
        tnumNode4 = (TNum)nodeArrayList3.get(0);

        pmodifierNode1 = new APlusModifier(tidentNode2, tplusNode3, tnumNode4);
        }
	nodeList.add(pmodifierNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new13() /* reduce AMinusModifier */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PModifier pmodifierNode1;
        {
            // Block
        TIdent tidentNode2;
        TMinus tminusNode3;
        TNum tnumNode4;
        tidentNode2 = (TIdent)nodeArrayList1.get(0);
        tminusNode3 = (TMinus)nodeArrayList2.get(0);
        tnumNode4 = (TNum)nodeArrayList3.get(0);

        pmodifierNode1 = new AMinusModifier(tidentNode2, tminusNode3, tnumNode4);
        }
	nodeList.add(pmodifierNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new14() /* reduce AEqualModifier */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PModifier pmodifierNode1;
        {
            // Block
        TIdent tidentNode2;
        TEqual tequalNode3;
        TNum tnumNode4;
        tidentNode2 = (TIdent)nodeArrayList1.get(0);
        tequalNode3 = (TEqual)nodeArrayList2.get(0);
        tnumNode4 = (TNum)nodeArrayList3.get(0);

        pmodifierNode1 = new AEqualModifier(tidentNode2, tequalNode3, tnumNode4);
        }
	nodeList.add(pmodifierNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new15() /* reduce ATerminal$Variabledef */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        LinkedList<Object> listNode2 = new LinkedList<Object>();
        {
            // Block
        PVariabledef pvariabledefNode1;
        pvariabledefNode1 = (PVariabledef)nodeArrayList1.get(0);
	if(pvariabledefNode1 != null)
	{
	  listNode2.add(pvariabledefNode1);
	}
        }
	nodeList.add(listNode2);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new16() /* reduce ANonTerminal$Variabledef */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        LinkedList<Object> listNode3 = new LinkedList<Object>();
        {
            // Block
        LinkedList<Object> listNode1 = new LinkedList<Object>();
        PVariabledef pvariabledefNode2;
        listNode1 = (LinkedList)nodeArrayList1.get(0);
        pvariabledefNode2 = (PVariabledef)nodeArrayList2.get(0);
	if(listNode1 != null)
	{
	  listNode3.addAll(listNode1);
	}
	if(pvariabledefNode2 != null)
	{
	  listNode3.add(pvariabledefNode2);
	}
        }
	nodeList.add(listNode3);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new17() /* reduce ATerminal$Eventdef */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        LinkedList<Object> listNode2 = new LinkedList<Object>();
        {
            // Block
        PEventdef peventdefNode1;
        peventdefNode1 = (PEventdef)nodeArrayList1.get(0);
	if(peventdefNode1 != null)
	{
	  listNode2.add(peventdefNode1);
	}
        }
	nodeList.add(listNode2);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new18() /* reduce ANonTerminal$Eventdef */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        LinkedList<Object> listNode3 = new LinkedList<Object>();
        {
            // Block
        LinkedList<Object> listNode1 = new LinkedList<Object>();
        PEventdef peventdefNode2;
        listNode1 = (LinkedList)nodeArrayList1.get(0);
        peventdefNode2 = (PEventdef)nodeArrayList2.get(0);
	if(listNode1 != null)
	{
	  listNode3.addAll(listNode1);
	}
	if(peventdefNode2 != null)
	{
	  listNode3.add(peventdefNode2);
	}
        }
	nodeList.add(listNode3);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new19() /* reduce ATerminal$Exitstm */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        LinkedList<Object> listNode2 = new LinkedList<Object>();
        {
            // Block
        PExitstm pexitstmNode1;
        pexitstmNode1 = (PExitstm)nodeArrayList1.get(0);
	if(pexitstmNode1 != null)
	{
	  listNode2.add(pexitstmNode1);
	}
        }
	nodeList.add(listNode2);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new20() /* reduce ANonTerminal$Exitstm */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        LinkedList<Object> listNode3 = new LinkedList<Object>();
        {
            // Block
        LinkedList<Object> listNode1 = new LinkedList<Object>();
        PExitstm pexitstmNode2;
        listNode1 = (LinkedList)nodeArrayList1.get(0);
        pexitstmNode2 = (PExitstm)nodeArrayList2.get(0);
	if(listNode1 != null)
	{
	  listNode3.addAll(listNode1);
	}
	if(pexitstmNode2 != null)
	{
	  listNode3.add(pexitstmNode2);
	}
        }
	nodeList.add(listNode3);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new21() /* reduce ATerminal$Modifier */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        LinkedList<Object> listNode2 = new LinkedList<Object>();
        {
            // Block
        PModifier pmodifierNode1;
        pmodifierNode1 = (PModifier)nodeArrayList1.get(0);
	if(pmodifierNode1 != null)
	{
	  listNode2.add(pmodifierNode1);
	}
        }
	nodeList.add(listNode2);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new22() /* reduce ANonTerminal$Modifier */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        LinkedList<Object> listNode3 = new LinkedList<Object>();
        {
            // Block
        LinkedList<Object> listNode1 = new LinkedList<Object>();
        PModifier pmodifierNode2;
        listNode1 = (LinkedList)nodeArrayList1.get(0);
        pmodifierNode2 = (PModifier)nodeArrayList2.get(0);
	if(listNode1 != null)
	{
	  listNode3.addAll(listNode1);
	}
	if(pmodifierNode2 != null)
	{
	  listNode3.add(pmodifierNode2);
	}
        }
	nodeList.add(listNode3);
        return nodeList;
    }



    private static int[][][] actionTable;
/*      {
			{{-1, REDUCE, 0}, {9, SHIFT, 1}, {11, SHIFT, 2}, },
			{{-1, ERROR, 1}, {15, SHIFT, 8}, },
			{{-1, ERROR, 2}, {15, SHIFT, 9}, },
			{{-1, ERROR, 3}, {16, ACCEPT, -1}, },
			{{-1, REDUCE, 15}, },
			{{-1, REDUCE, 17}, },
			{{-1, REDUCE, 1}, {9, SHIFT, 1}, {11, SHIFT, 2}, },
			{{-1, REDUCE, 2}, {11, SHIFT, 2}, },
			{{-1, ERROR, 8}, {12, SHIFT, 13}, },
			{{-1, ERROR, 9}, {8, SHIFT, 14}, },
			{{-1, REDUCE, 16}, },
			{{-1, REDUCE, 3}, {11, SHIFT, 2}, },
			{{-1, REDUCE, 18}, },
			{{-1, ERROR, 13}, {14, SHIFT, 15}, },
			{{-1, ERROR, 14}, {4, SHIFT, 16}, },
			{{-1, ERROR, 15}, {14, SHIFT, 18}, },
			{{-1, ERROR, 16}, {5, SHIFT, 19}, {10, SHIFT, 20}, },
			{{-1, REDUCE, 5}, },
			{{-1, ERROR, 18}, {14, SHIFT, 23}, },
			{{-1, REDUCE, 6}, },
			{{-1, ERROR, 20}, {14, SHIFT, 24}, },
			{{-1, REDUCE, 19}, },
			{{-1, ERROR, 22}, {5, SHIFT, 25}, {10, SHIFT, 20}, },
			{{-1, REDUCE, 4}, },
			{{-1, ERROR, 24}, {6, SHIFT, 27}, },
			{{-1, REDUCE, 7}, },
			{{-1, REDUCE, 20}, },
			{{-1, ERROR, 27}, {15, SHIFT, 28}, },
			{{-1, REDUCE, 8}, {2, SHIFT, 29}, },
			{{-1, ERROR, 29}, {3, SHIFT, 31}, {15, SHIFT, 32}, },
			{{-1, REDUCE, 9}, },
			{{-1, REDUCE, 10}, },
			{{-1, ERROR, 32}, {0, SHIFT, 35}, {1, SHIFT, 36}, {7, SHIFT, 37}, },
			{{-1, REDUCE, 21}, },
			{{-1, ERROR, 34}, {3, SHIFT, 38}, {15, SHIFT, 32}, },
			{{-1, ERROR, 35}, {14, SHIFT, 40}, },
			{{-1, ERROR, 36}, {14, SHIFT, 41}, },
			{{-1, ERROR, 37}, {14, SHIFT, 42}, },
			{{-1, REDUCE, 11}, },
			{{-1, REDUCE, 22}, },
			{{-1, REDUCE, 12}, },
			{{-1, REDUCE, 13}, },
			{{-1, REDUCE, 14}, },
        };*/
    private static int[][][] gotoTable;
/*      {
			{{-1, 3}, },
			{{-1, 4}, {6, 10}, },
			{{-1, 5}, {7, 12}, {11, 12}, },
			{{-1, 17}, },
			{{-1, 21}, {22, 26}, },
			{{-1, 30}, },
			{{-1, 33}, {34, 39}, },
			{{-1, 6}, },
			{{-1, 7}, {6, 11}, },
			{{-1, 22}, },
			{{-1, 34}, },
        };*/
    private static String[] errorMessages;
/*      {
			"expecting: 'var', 'event', EOF",
			"expecting: ident",
			"expecting: EOF",
			"expecting: 'event', EOF",
			"expecting: visibility",
			"expecting: ':'",
			"expecting: num",
			"expecting: '{'",
			"expecting: '}', 'exit'",
			"expecting: '->'",
			"expecting: '[', '}', 'exit'",
			"expecting: ']', ident",
			"expecting: '+', '-', '='",
        };*/
    private static int[] errors;
/*      {
			0, 1, 1, 2, 0, 3, 0, 3, 4, 5, 0, 3, 3, 6, 7, 6, 8, 3, 6, 3, 6, 8, 8, 0, 9, 3, 8, 1, 10, 11, 8, 8, 12, 11, 11, 6, 6, 6, 8, 11, 11, 11, 11, 
        };*/

    static 
    {
        try
        {
            DataInputStream s = new DataInputStream(
                new BufferedInputStream(
                Parser.class.getResourceAsStream("parser.dat")));

            // read actionTable
            int length = s.readInt();
            Parser.actionTable = new int[length][][];
            for(int i = 0; i < Parser.actionTable.length; i++)
            {
                length = s.readInt();
                Parser.actionTable[i] = new int[length][3];
                for(int j = 0; j < Parser.actionTable[i].length; j++)
                {
                for(int k = 0; k < 3; k++)
                {
                    Parser.actionTable[i][j][k] = s.readInt();
                }
                }
            }

            // read gotoTable
            length = s.readInt();
            gotoTable = new int[length][][];
            for(int i = 0; i < gotoTable.length; i++)
            {
                length = s.readInt();
                gotoTable[i] = new int[length][2];
                for(int j = 0; j < gotoTable[i].length; j++)
                {
                for(int k = 0; k < 2; k++)
                {
                    gotoTable[i][j][k] = s.readInt();
                }
                }
            }

            // read errorMessages
            length = s.readInt();
            errorMessages = new String[length];
            for(int i = 0; i < errorMessages.length; i++)
            {
                length = s.readInt();
                StringBuffer buffer = new StringBuffer();

                for(int j = 0; j < length; j++)
                {
                buffer.append(s.readChar());
                }
                errorMessages[i] = buffer.toString();
            }

            // read errors
            length = s.readInt();
            errors = new int[length];
            for(int i = 0; i < errors.length; i++)
            {
                errors[i] = s.readInt();
            }

            s.close();
        }
        catch(Exception e)
        {
            throw new RuntimeException("The file \"parser.dat\" is either missing or corrupted.");
        }
    }
}
