/* This file was generated by SableCC (http://www.sablecc.org/). */

package oog.syntax.parser;

import oog.syntax.node.*;
import oog.syntax.analysis.*;

class TokenIndex extends AnalysisAdapter
{
    int index;

    @Override
    public void caseTPlus(@SuppressWarnings("unused") TPlus node)
    {
        this.index = 0;
    }

    @Override
    public void caseTMinus(@SuppressWarnings("unused") TMinus node)
    {
        this.index = 1;
    }

    @Override
    public void caseTLSqPar(@SuppressWarnings("unused") TLSqPar node)
    {
        this.index = 2;
    }

    @Override
    public void caseTRSqPar(@SuppressWarnings("unused") TRSqPar node)
    {
        this.index = 3;
    }

    @Override
    public void caseTLBrace(@SuppressWarnings("unused") TLBrace node)
    {
        this.index = 4;
    }

    @Override
    public void caseTRBrace(@SuppressWarnings("unused") TRBrace node)
    {
        this.index = 5;
    }

    @Override
    public void caseTArrow(@SuppressWarnings("unused") TArrow node)
    {
        this.index = 6;
    }

    @Override
    public void caseTEqual(@SuppressWarnings("unused") TEqual node)
    {
        this.index = 7;
    }

    @Override
    public void caseTDotDot(@SuppressWarnings("unused") TDotDot node)
    {
        this.index = 8;
    }

    @Override
    public void caseTVar(@SuppressWarnings("unused") TVar node)
    {
        this.index = 9;
    }

    @Override
    public void caseTExit(@SuppressWarnings("unused") TExit node)
    {
        this.index = 10;
    }

    @Override
    public void caseTEvent(@SuppressWarnings("unused") TEvent node)
    {
        this.index = 11;
    }

    @Override
    public void caseTVisibility(@SuppressWarnings("unused") TVisibility node)
    {
        this.index = 12;
    }

    @Override
    public void caseTDefault(@SuppressWarnings("unused") TDefault node)
    {
        this.index = 13;
    }

    @Override
    public void caseTNum(@SuppressWarnings("unused") TNum node)
    {
        this.index = 14;
    }

    @Override
    public void caseTIdent(@SuppressWarnings("unused") TIdent node)
    {
        this.index = 15;
    }

    @Override
    public void caseEOF(@SuppressWarnings("unused") EOF node)
    {
        this.index = 16;
    }
}
