/* This file was generated by SableCC (http://www.sablecc.org/). */

package event.syntax.node;

import java.util.*;
import event.syntax.analysis.*;

@SuppressWarnings("nls")
public final class AProgram extends PProgram
{
    private final LinkedList<PEvent> _events_ = new LinkedList<PEvent>();

    public AProgram()
    {
        // Constructor
    }

    public AProgram(
        @SuppressWarnings("hiding") List<?> _events_)
    {
        // Constructor
        setEvents(_events_);

    }

    @Override
    public Object clone()
    {
        return new AProgram(
            cloneList(this._events_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAProgram(this);
    }

    public LinkedList<PEvent> getEvents()
    {
        return this._events_;
    }

    public void setEvents(List<?> list)
    {
        for(PEvent e : this._events_)
        {
            e.parent(null);
        }
        this._events_.clear();

        for(Object obj_e : list)
        {
            PEvent e = (PEvent) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._events_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._events_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._events_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        for(ListIterator<PEvent> i = this._events_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PEvent) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
