/* This file was generated by SableCC (http://www.sablecc.org/). */

package event.syntax.node;

import event.syntax.analysis.*;

@SuppressWarnings("nls")
public final class TFile extends Token
{
    public TFile()
    {
        super.setText("file");
    }

    public TFile(int line, int pos)
    {
        super.setText("file");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TFile(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTFile(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TFile text.");
    }
}
