/* This file was generated by SableCC (http://www.sablecc.org/). */

package event.syntax.node;

import event.syntax.analysis.*;

@SuppressWarnings("nls")
public final class TFirst extends Token
{
    public TFirst()
    {
        super.setText("first");
    }

    public TFirst(int line, int pos)
    {
        super.setText("first");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TFirst(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTFirst(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TFirst text.");
    }
}
