/* This file was generated by SableCC (http://www.sablecc.org/). */

package event.syntax.parser;

import event.syntax.node.*;
import event.syntax.analysis.*;

class TokenIndex extends AnalysisAdapter
{
    int index;

    @Override
    public void caseTLBrace(@SuppressWarnings("unused") TLBrace node)
    {
        this.index = 0;
    }

    @Override
    public void caseTRBrace(@SuppressWarnings("unused") TRBrace node)
    {
        this.index = 1;
    }

    @Override
    public void caseTDotDot(@SuppressWarnings("unused") TDotDot node)
    {
        this.index = 2;
    }

    @Override
    public void caseTFirst(@SuppressWarnings("unused") TFirst node)
    {
        this.index = 3;
    }

    @Override
    public void caseTExit(@SuppressWarnings("unused") TExit node)
    {
        this.index = 4;
    }

    @Override
    public void caseTFile(@SuppressWarnings("unused") TFile node)
    {
        this.index = 5;
    }

    @Override
    public void caseTNum(@SuppressWarnings("unused") TNum node)
    {
        this.index = 6;
    }

    @Override
    public void caseTIdent(@SuppressWarnings("unused") TIdent node)
    {
        this.index = 7;
    }

    @Override
    public void caseTString(@SuppressWarnings("unused") TString node)
    {
        this.index = 8;
    }

    @Override
    public void caseEOF(@SuppressWarnings("unused") EOF node)
    {
        this.index = 9;
    }
}
