/* This file was generated by SableCC (http://www.sablecc.org/). */

package event.syntax.analysis;

import event.syntax.node.*;

public interface Analysis extends Switch
{
    Object getIn(Node node);
    void setIn(Node node, Object o);
    Object getOut(Node node);
    void setOut(Node node, Object o);

    void caseStart(Start node);
    void caseAProgram(AProgram node);
    void caseAFirstEvent(AFirstEvent node);
    void caseANormalEvent(ANormalEvent node);
    void caseAAgregation(AAgregation node);
    void caseADirectAssosiation(ADirectAssosiation node);
    void caseAIndirectAssosiation(AIndirectAssosiation node);
    void caseAChoiceAssosiation(AChoiceAssosiation node);

    void caseTLBrace(TLBrace node);
    void caseTRBrace(TRBrace node);
    void caseTDotDot(TDotDot node);
    void caseTFirst(TFirst node);
    void caseTExit(TExit node);
    void caseTFile(TFile node);
    void caseTNum(TNum node);
    void caseTIdent(TIdent node);
    void caseTComment(TComment node);
    void caseTBlank(TBlank node);
    void caseTString(TString node);
    void caseEOF(EOF node);
    void caseInvalidToken(InvalidToken node);
}
